### ISSUE TITLE
Columnname whitespace removal is surprising

### ISSUE THREAD

**Issue by lmeyerov** [Gmousse/dataframe-js#14]
Currently, the first whitespace in a column name is removed. I think this is a minor bug in that it was intended to be a global replace. However, there are two deeper design issues here:

* Can whitespace removal be dropped? This makes reuse with externally defined column names error-prone. AFAICT, only the constructor needs that modification.

* If column renaming is not dropped, can we expose the renaming in some way so that external code can track how to map + reverse map names?

Happy to contribute code here, lmk.

**Comment by Gmousse** [comment]
Hello.
Thanks for submitting this interesting issue.

I have add this white space removal (honestly I forgot its existence) when I have developed the SQL module, due to different bugs while parsing column names with spaces.
But anyways it's a bug (and a miss-conception ? 👎 ) and the DataFrame object should not handle this type of data treatments for his modules. 

Tomorrow I will create a pr and then a hotfix (1.1.2) resolving your issue and other little things I want to change on SQL module.

OFC this hotfix will doesn't contain breaking changes.

Stay tuned !

**Comment by lmeyerov** [comment]
Thanks. Feel free to use this edit: https://github.com/graphistry/dataframe-js 

I couldn't get it to pass the test suite some reason, so worth checking that.

**Comment by Gmousse** [comment]
I have merged your fork on a pull request. I will close it this night if I can.

**Comment by Gmousse** [comment]
@lmeyerov The Hotfix 1.1.2 is published (git or npm) with the patch on DataFrame and on SQL.
The issue can now be closed thanks to you.
