### ISSUE TITLE
Performance of queries (indexes on columns)

### ISSUE THREAD

**Issue by CMCDragonkai** [Gmousse/dataframe-js#34]
Is there a way to establish indexes on columns to speed up access queries based on where conditions?

**Comment by CMCDragonkai** [comment]
I'm looking at other database libraries in JS, but none of them are immutable or fully persistent.

**Comment by Gmousse** [comment]
Hi @CMCDragonkai,
Currently there is no indexation on DataFrame.
But I m working on it for a next big big release with other massive optimizations (currently dataframe-js is stable but not well optimized).

I will create issues with the next features I will implement in order to allow you (and other users) to follow these.

**Comment by CMCDragonkai** [comment]
Cool, for now I'll be investigating datascript.
