### ISSUE TITLE
Dataframe from file examples 

### ISSUE THREAD

**Issue by cjohns38** [Gmousse/dataframe-js#50]
I'm familiar with data frames through R and python so I was looking for something similar in JS.  I ran into this module.  The problem I'm having is that when I try and read in a local JS file it's returning a promise not an actual DF.  If I run the following a DF doesn't really seem to be created. 

```
var DataFrame = dfjs.Dataframe; 

const df = new DataFrame.fromJSON('http://localhost:8000/data/maps3.json').then(df => df); 

df.show()  // returns df.show is not a function 
```

If I run this the DF is displayed so I know it's not a read error but something about how the DF is being created.

```
var DataFrame = dfjs.Dataframe; 

// Actually shows the DF 
const df = new DataFrame.fromJSON('http://localhost:8000/data/maps3.json').then( df => {df.show()} ); 

```
As best I can tell this has to do with a promise being created not the actual DF.  If I use the following it functions as I would expect. 

```
// From a collection (easier)
const df = new DataFrame([
    {c1: 1, c2: 6}, // <------- A row
    {c4: 1, c3: 2}
], ['c1', 'c2', 'c3', 'c4']);

df.show()
```

**Request 1**: When reading in the json file like above, how do I return the DF object? Can you update the basic usage documentation help illustrate how to handle reading the file in and returning a DF? Maybe I'm missing something simple?

**Request/Question 2**: When I use df.select('column') it returns an object when I would have expected it to return a list or vector of the values.  Is there simple method for doing that?  If so, can you provide an example in your documentation?

FYI, I'm looking to take JSONS, convert to DFs, and then manipulate and subset the data and then feed it into D3 to make some interactive dashboards. Between some basic JS on the page, DFs and what they can do, and D3 I think there are some great opporunities, I just need to get the DF portion ironed out.

**Comment by Gmousse** [comment]
Hi,

Indeed it seems you are a beginner in javascript.

To be clear, a Promise (like a callback on d3-request or simply ajax calls) is asynchronous and non-blocking. The whole javascript is async during I/O. Indeed, when you make a call to the filesystem (except for fs.readFileSync), a database or to an http(s) endpoint, the rest of the code will be triggered (in the .then) when the result comes.

When you create a DataFrame from js code (not an I/O), you are synchronous. When you ask to load file or to call an api endpoint, your are asynchronous.

As for example if you want to do asynchronous stuff (not in DataFrame but just in js)

````javascript
function yourCode(data) {
    console.log("my data is ready");
}

mypromise.then(yourCode);  // yourCall will be called when the data comes. It's non-blocking
console.log("my data is called"); // this console.log can be called before yourCode

````
To conclude with dataframe-js:

````javascript
function myComputation(df) {
    const newdf = df.groupBy("id").count();
    df.show(); 
}

DataFrame.fromJSON(yourPath).then(myComputation) // myComputation is asynchronous and will be called when the data is loaded and the DataFrame created.

console.log(df) // It does not work because df can't be accessed outside the Promise, and also because at this moment, the promise is maybe not resolved.
````

It's not due to dataframe-js but javascript asynchronous philosophy.

I suggest you to read js books, to follow courses or simply have a look on js examples (https://github.com/Gmousse/dataframe-js/blob/develop/examples/titanic_analysis.js).

Some good sources to understand promises:
http://exploringjs.com/es6/ch_promises.html
https://www.discovermeteor.com/blog/understanding-sync-async-javascript-node/

Have fun and thanks to use dataframe-js.

**Comment by jahnavi9299p** [comment]
Hello,
I am beginner to JS and yet am being ambitious to deal with datafraem-js. However I have experience in python datframes.
I have followed the example on github which worked perfectly fine for me.
However I have problem open my own dataframe ....


const DataFrame = require("dataframe-js").DataFrame;
DataFrame.fromCSV(
    "Sample.csv"
)
    .then(df => {
        // Let's go to display quicly our table.
        // df.show();
        console.log(df.listColumns());
    }
    )


which returns [ 'Error: connect ECONNREFUSED 127.0.0.1:80' ] on PowerShell and GitBash.
What went wrong?
